config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  get :login, to: 'sessions#new'
  get :signup, to: 'users#new'
  delete :logout, to: 'sessions#destroy'

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true

  has_many :answers
  belongs_to :test
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :find_test, only: %i[create new index]
  before_action :find_question, only: %i[edit show update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
  def new
    @question = @test.questions.new
  end

  def edit; end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def show; end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to @question.test
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Вопрос не найден'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create new '#{question.test.title}' question"
    elsif question.persisted?
      "Edit '#{question.test.title}' question"
    end
  end
end

app/views/questions/_form.html.erb
<h1><%= question_header(@question) %></h1>

<%= form_with model: [@test, @question], local: true do |form| %>
  <%= render 'shared/error', resource: @question %>

  <p>
    <%= form.label :content %><br>
    <%= form.text_field :content, id: :question_content %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/questions/_question.html.erb
<tr>
    <td><%= question.body %></td>
    <td><%= link_to 'Показать', question_path(question) %></td>
    <td><%= link_to 'Изменить', edit_question_path(question) %></td>
    <td><%= link_to 'Удалить',
                    question_path(question),
                    method: :delete,
                    data: {confirm: 'Вы уверены?'} %>
</tr>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<%= render 'shared/questions', test: @test %>

app/views/questions/new.html.erb
<h1>Новый вопрос</h1>

<%= form_with model: @question, url: test_questions_path(params[:test_id]) do |f| %>
  <div>
    <%= f.label :body %><br>
    <%= f.text_field :body %><br>
  </div>

  <div>
    <%= f.submit "Создать" %>
  </div>

<% end %> 

app/views/questions/show.html.erb
<h1><%= @question.test.title %> Question</h1>

<p>
  <strong>Question:</strong>
  <%= @question.body %>
</p>

<h2>Answers</h2>
<%= link_to 'Новый ответ', new_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'Назад', @question.test %>