config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  get :login, to: 'sessions#new'
  get :signup, to: 'users#new'
  delete :logout, to: 'sessions#destroy'

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true

  has_many :answers
  belongs_to :test
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASS_TEST_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  def success?
    percentage_of_correct_answers >= PASS_TEST_PERCENT
  end

  def percentage_of_correct_answers
    (correct_questions.to_f / test.questions.count.to_f) * 100
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  private

  def before_validation_set_current_question
    self.current_question =
      if current_question.nil?
        test.questions.first if test.present?
      else
        test.questions.order(:id).where('id > ?', current_question.id).first
      end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :find_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1>The <%= @test_passage.test.title %> Test was Completed</h1>
<% if @test_passage.success? %>
  <p >Your score <span class="color_green"><%= @test_passage.percentage_of_correct_answers %></span>%. Test passed.</p>
<% else %>
<p>Your score <span class="color_red"><%= @test_passage.percentage_of_correct_answers %></span>%. Try again.</p>
<% end %>
<%= link_to 'Back to tests', tests_path %>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title%> Test</h1>

<b>
  (
  <%= @test_passage.current_question_number %> of
  <%= @test_passage.test.questions.count %>
)
<%= @test_passage.current_question.body %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
<%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
  <p>
    <%= b.check_box id: "answer_ids_#{b.object.id}" %>
    <%= b.label %>
  </p>
<% end %>

<p><%= form.submit 'Следующий' %></p>
<% end %>