config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  get :login, to: 'sessions#new'
  get :signup, to: 'users#new'
  delete :logout, to: 'sessions#destroy'

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end
end

app/views/shared/_error.html.erb
<% if resource.errors.present? %>
  <div>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div>
  <hr>
  <p>
  <%= link_to 'Test-Guru', 'https://github.com/Sevos83/test-guru' %> | Author: Александр Севостьянов
  </p>

  <p>
  Платформа для прохождения, просмотра, создания тестов Test-Guru
  </p>

  <p>
  <%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com/', target: :_blank %>
  <%= current_year %>
  </p>
</div>

app/views/shared/_navbar.html.erb
<p class="nav user"><%= link_to 'Тест Гуру', root_path %></p>
<% if logged_in? %>
  <p class="nav user">
    Добро пожаловать, <b><%= current_user.name %></b> Гуру<br>
    <%= link_to 'Выход', logout_path, method: :delete %>
  </p>
<% else %>
  <p class="nav user">
    <%= link_to 'Регистрация', signup_path %> |
    <%= link_to 'Войти', login_path %>
  </p>
<% end %>

app/views/shared/_questions.html.erb
<h1>All questions of test '<%=@test.title %>'</h1>

<p><%= link_to 'Create new question for this test', new_test_question_path(@test) %></p>

<table>
  <tr>
    <th>Question content</th>
    <th colspan=3>Actions</th>
  </tr>
  <%= render @test.questions %>
</table>