config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  get :login, to: 'sessions#new'
  get :signup, to: 'users#new'
  delete :logout, to: 'sessions#destroy'

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true
  validate :validate_numbers_of_answers, on: :create

  belongs_to :question

  scope :correct_answer, -> { where(correct: true) }

  private

  def validate_numbers_of_answers
    message = 'Кол-во ответов может быть не больше 4-х'
    errors.add(:question, message) if question.answers.count >= 4
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to @answer
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to 'Показать', answer_path(answer) %>
  <%= link_to 'Изменить', edit_answer_path(answer) %>
  <%= link_to 'Удалить', answer_path(answer),
               method: :delete,
               data: { confirm: 'Вы уверены?' } %>
</li> 

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer], local: true do |form| %>
 <%= render 'shared/error', resource: @answer %>

 <p>
   <%= form.label :body %><br>
   <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
 </p>

 <p>
   <%= form.label :correct %>
   <%= form.check_box :correct, id: :answer_correct %>
 </p>

  <p><%= form.submit %></p>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>
<%= link_to 'Back', question_path(@answer.question) %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>
<%= link_to 'Back', question_path(@question) %>

app/views/answers/show.html.erb
<h1>Вопрос</h1>

</p>
  <%= @answer.question.body %>
<p>

<p>
  <b>Ответ:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Правельный:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Назад', question_path(@answer.question) %>